name:                compact-coupled-terms
version:             0.1.0.0
github:              "githubuser/compact-coupled-terms"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/compact-coupled-terms#readme>

dependencies:
- base >= 4.7 && < 5
default-extensions:
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - PatternGuards
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
library:
  source-dirs: src
  dependencies:
    - array
    - containers
    - equivalence
    - fgl
    - hashable
    - hashtables
    - ilist
    - intern
    - language-dot
    - lens
    - mtl
    - pretty-simple
    - raw-strings-qq
    - text
    - unordered-containers

executables:
  compact-coupled-terms-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compact-coupled-terms
    - language-dot

tests:
  unit-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base
      - compact-coupled-terms
      - hashable
      - hspec
      - text